# Site wide configuration

title: Théa Ragon
bio: "Postdoc at Caltech - Earthquakes, faults and inverse problems"
locale: en_US
url: thearagon.github.io
image:
  feature: 
baseurl: /thearagon.github.io

# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Théa Ragon
  avatar: portrait.jpg
  bio: "Postdoc at Caltech - Earthquakes, faults and inverse problems"
  github: thearagon
  bitbucket: #username
  orcid: 0000-0002-1276-1910
  scholar: v_X3_GoAAAAJ
  mendeley: #username
  researchgate: Thea_Ragon
  stackoverflow: #http://stackoverflow.com/users/123456/username
  email:
  disqus-shortname: #username
  twitter: thea_ragon
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  linkedin: thearagon
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
